site_name: Zodiax
site_url: https://louisdesdoigts.github.io/zodiax/
site_description: Documentation for Zodiax.
site_author: Louis Desdoigts
repo_url: https://github.com/LouisDesdoigts/zodiax
repo_name: LouisDesdoigts/zodiax

# Zensical uses the Material look by default but faster
theme:
  name: zensical 
  icon:
    repo: fontawesome/brands/github  # Sets the logo to the GitHub 'cat'
  features:
    # - navigation.sections  # Groups top-level items into sections
    - navigation.top      # "Back to top" button
    - navigation.indexes   # Allows a section title to be its own page
    - content.code.copy   # Copy button on code blocks
    - toc.integrate       # Put Table of Contents on the left sidebar
    - content.action.edit   # Adds an "Edit this page" button
    - content.action.view   # Adds a "View source" button
  palette:
    # Light mode
    - scheme: default
      primary: amber
      accent: orange
      toggle:
        icon: lucide/sun
        name: Switch to dark mode
    # Dark mode
    - scheme: slate
      primary: amber
      accent: orange
      toggle:
        icon: lucide/moon
        name: Switch to light mode

edit_uri: edit/main/docs/   # Directs where the "Edit" link points

plugins:
  - zensical/search      # High-performance built-in search
  - mkdocstrings:        # Auto-generate API docs from code
      handlers:
        python:
          options:
            docstring_style: "numpy"
            show_root_heading: true      # Highly recommended for module-level docs
extra:
  version:
    provider: mike  # Tells the UI: "Look for mike's version list"

markdown_extensions:
  - admonition           # Support for !!! note "Title" blocks
  - pymdownx.details     # Support for collapsible ??? note blocks
  - pymdownx.superfences # Allows nesting code inside other blocks
  - pymdownx.snippets:
      base_path: [".", "docs"] # Look in the root AND the docs folder
  - pymdownx.arithmatex: # Required for LaTeX math
      generic: true
  - toc:
      permalink: "¤"     # Clickable link next to headers
  - attr_list            # Required to resize/style images {: width=300}
  - md_in_html           # Allows using HTML tags inside Markdown


# MathJax setup for LaTeX rendering
extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Navigation map
nav:
  - Overview: 
      - index.md
  - Using Zodiax: 
      - Building Classes: usage.md
      - Optimisation: optimisation_tools.md
  - API:
      - Base: API/base.md
      - Optimisation: API/optimisation.md
      - Stats: API/stats.md
      - Batching: API/batching.md
      - Tree: API/tree.md
      - Fisher: API/fisher.md
      - Equinox (eqx): API/eqx.md
  - Previous Versions:
      - v0.4.1: https://louisdesdoigts.github.io/zodiax/0.4.1/
  - FAQ: faq.md
  - Changelog: CHANGELOG.md
