name: automated tests
on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - name: checkout
        uses: actions/checkout@main

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: install environment
        run: |
          python -m pip install --upgrade pip
          pip install --quiet pytest
          pip install --quiet -r requirements.txt
          pip install --quiet .

      # ===== Tests =====
      - name: base tests
        run: pytest --quiet tests/test_base.py
      - name: equinox tests
        run: pytest --quiet tests/test_equinox.py
      - name: equinox tree
        run: pytest --quiet tests/test_tree.py
      - name: equinox optimisation
        run: pytest --quiet tests/test_optimisation.py
      - name: equinox serialisation
        run: pytest --quiet tests/test_serialisation.py